const initialCards = [
    {
        link: './images/Darman.png',
        linkname:'горная мята',
        name: 'DARMAN горная мята',
        artikul:'Артикул',
        artikulznach:'123123',
        sostav:'Состав',
        sostavznach:'мята 100%',
        upakovka:'Упаковка',
        upakovkaznach:'бумажный пакет',
        ves:'Вес товара без упаковки',
        vesznac:'20 г.',
        parametru:'Параметры упаковки',
        parametruznac:'13x11.5x5см',
        strana:'Страна производитель',
        stranaznach:'Армения'
    },
    {
        link: './images/Darman1.png',
        linkname:'',
        name: 'DARMAN горная зизифора',
        artikul:'',
        artikulznach:'',
        sostav:'',
        sostavznach:'',
        upakovka:'',
        upakovkaznach:'',
        ves:'',
        vesznac:'',
        parametru:'',
        parametruznac:'',
        strana:'',
        stranaznach:''
    },
    {
        link: './images/Darman2.png',
        linkname:'',
        name: 'DARMAN горный чабрец',
        artikul:'',
        artikulznach:'',
        sostav:'',
        sostavznach:'',
        upakovka:'',
        upakovkaznach:'',
        ves:'',
        vesznac:'',
        parametru:'',
        parametruznac:'',
        strana:'',
        stranaznach:''
    },
    {
        link: './images/Darman3.png',
        linkname:'',
        name: 'DARMAN горная душица',
        artikul:'',
        artikulznach:'',
        sostav:'',
        sostavznach:'',
        upakovka:'',
        upakovkaznach:'',
        ves:'',
        vesznac:'',
        parametru:'',
        parametruznac:'',
        strana:'',
        stranaznach:''
    },
    {
        link: './images/Darman4.png',
        linkname:'',
        name: 'DARMAN горная зизифора',
        artikul:'',
        artikulznach:'',
        sostav:'',
        sostavznach:'',
        upakovka:'',
        upakovkaznach:'',
        ves:'',
        vesznac:'',
        parametru:'',
        parametruznac:'',
        strana:'',
        stranaznach:''
    },
    {
        link: './images/Darman7.png',
        linkname:'',
        name: 'DARMAN горная зизифора',
        artikul:'',
        artikulznach:'',
        sostav:'',
        sostavznach:'',
        upakovka:'',
        upakovkaznach:'',
        ves:'',
        vesznac:'',
        parametru:'',
        parametruznac:'',
        strana:'',
        stranaznach:''
    },
    {
        link: '',
        linkname:'',
        name: 'Подарочный сундук DARMAN 4 вкуса',
        artikul:'',
        artikulznach:'',
        sostav:'',
        sostavznach:'',
        upakovka:'',
        upakovkaznach:'',
        ves:'',
        vesznac:'',
        parametru:'',
        parametruznac:'',
        strana:'',
        stranaznach:''
    },
    {
        link: '',
        linkname:'',
        name: 'Подарочный набор DARMAN 9 вкусов',
        artikul:'',
        artikulznach:'',
        sostav:'',
        sostavznach:'',
        upakovka:'',
        upakovkaznach:'',
        ves:'',
        vesznac:'',
        parametru:'',
        parametruznac:'',
        strana:'',
        stranaznach:''
    }
];